version: "3.9"

services:
  core-db:
    image: postgres
    container_name: core-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - core_pgdata:/var/lib/postgresql/data

  user-db:
    image: postgres
    container_name: user-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - user_pgdata:/var/lib/postgresql/data

  solid-queue:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: queue
    stdin_open: true
    tty: true
    command: bundle exec rake solid_queue:start
    depends_on:
      - core-db
      - user-db
    environment:
      - RAILS_ENV=development
      - CORE_DB_HOST=core-db
      - CORE_DB_PORT=5432
      - USER_DB_HOST=user-db
      - USER_DB_PORT=5432
    volumes:
      - .:/rails
      - gem_cache:/gems

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@pg.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - core-db
      - user-db
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  core_pgdata:
  user_pgdata:
  pgadmin-data:
  gem_cache:
